export const EUROVISION_FLAGS: Record<string, string> = {
  Sweden: '🇸🇪',
  Norway: '🇳🇴',
  Denmark: '🇩🇰',
  Finland: '🇫🇮',
  Iceland: '🇮🇸',
  Netherlands: '🇳🇱',
  Belgium: '🇧🇪',
  Germany: '🇩🇪',
  France: '🇫🇷',
  Spain: '🇪🇸',
  Portugal: '🇵🇹',
  Italy: '🇮🇹',
  Austria: '🇦🇹',
  Switzerland: '🇨🇭',
  Poland: '🇵🇱',
  'Czech Republic': '🇨🇿',
  Slovakia: '🇸🇰',
  Hungary: '🇭🇺',
  Romania: '🇷🇴',
  Bulgaria: '🇧🇬',
  Serbia: '🇷🇸',
  Croatia: '🇭🇷',
  Slovenia: '🇸🇮',
  Greece: '🇬🇷',
  Cyprus: '🇨🇾',
  Malta: '🇲🇹',
  Ireland: '🇮🇪',
  'United Kingdom': '🇬🇧',
  Ukraine: '🇺🇦',
  Lithuania: '🇱🇹',
  Latvia: '🇱🇻',
  Estonia: '🇪🇪',
  Israel: '🇮🇱',
  Australia: '🇦🇺',
  Albania: '🇦🇱',
  Armenia: '🇦🇲',
  Azerbaijan: '🇦🇿',
  Georgia: '🇬🇪',
  'North Macedonia': '🇲🇰',
  Montenegro: '🇲🇪',
  Moldova: '🇲🇩',
  'San Marino': '🇸🇲',
};

export const ALL_EUROVISION_COUNTRIES = Object.keys(EUROVISION_FLAGS);
