export const EUROVISION_FLAGS: Record<string, string> = {
  Sweden: '🇸🇪',
  Norway: '🇳🇴',
  Denmark: '🇩🇰',
  Finland: '🇫🇮',
  Austria: '🇦🇹',
  Belgium: '🇧🇪',
  Germany: '🇩🇪',
  France: '🇫🇷',
  Italy: '🇮🇹',
  Poland: '🇵🇱',
  'Czech Republic': '🇨🇿',
  Romania: '🇷🇴',
  Bulgaria: '🇧🇬',
  Serbia: '🇷🇸',
  Croatia: '🇭🇷',
  Greece: '🇬🇷',
  Cyprus: '🇨🇾',
  Malta: '🇲🇹',
  'United Kingdom': '🇬🇧',
  Ukraine: '🇺🇦',
  Lithuania: '🇱🇹',
  Israel: '🇮🇱',
  Australia: '🇦🇺',
  Albania: '🇦🇱',
  Moldova: '🇲🇩',
};

export const ALL_EUROVISION_COUNTRIES = Object.keys(EUROVISION_FLAGS);
